sudo: required
language: python
python:
  - "2.7"
cache:
  apt: true
addons:
  apt:
    packages:
      - xvfb
      - tree
      - git
      - wine
      - winetricks
      - scrot
      - flip
      - imagemagick

script: bash ./.travis.sh
