sudo: false
language: python
python:
  - "2.7"
cache:
  apt: true
addons:
  apt:
    packages:
      - tree
      - git
      - flip
      - imagemagick
      - curl
      - sed

script: bash ./.travis.sh
